# Generated by Django 3.1.4 on 2021-03-03 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import em.models

def load_init_data(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'em')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, '行政人員'), (1, '高中部教師'), (2, '國中部教師')], verbose_name='身分')),
                ('status', models.IntegerField(choices=[(0, '在職'), (1, '已離職'), (2, '留職停薪')], default=0, verbose_name='狀態')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('email', models.EmailField(max_length=128, verbose_name='電子郵件')),
                ('phone', models.CharField(max_length=32, verbose_name='聯絡電話')),
                ('oid', models.IntegerField(default=0, verbose_name='舊編號')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='設備編號')),
                ('prop_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='財產編號')),
                ('barcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='條碼序號')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '故障:待修'), (2, '故障:原廠送修'), (8, '故障:待報廢'), (9, '已報廢')], default=0, verbose_name='狀態')),
                ('oid', models.IntegerField(default=0, verbose_name='舊編號')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='盤點年度')),
                ('invlist', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='廠商名稱')),
                ('phone', models.CharField(max_length=32, verbose_name='聯絡電話')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='型號')),
                ('date_buy', models.DateField(verbose_name='購置日期')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='詳細規格')),
                ('status', models.IntegerField(choices=[(0, '列帳'), (1, '報廢除帳')], default=0, verbose_name='狀態')),
                ('category', models.IntegerField(choices=[(0, 'NB'), (1, 'PC'), (2, '攝影設備'), (3, '網路設備'), (4, '影音週邊'), (5, '其他週邊')], verbose_name='設備類別')),
                ('oid', models.IntegerField(default=0, verbose_name='舊編號')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=em.models.model_pic_name, verbose_name='圖片')),
                ('si', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='em.si')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_apply', models.DateField(verbose_name='借出日期')),
                ('date_return', models.DateField(blank=True, null=True, verbose_name='歸還日期')),
                ('oid', models.IntegerField(default=0, verbose_name='舊編號')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登錄人')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='em.equip', verbose_name='設備')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='em.applicant', verbose_name='借用人')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked', models.DateTimeField(auto_now=True, verbose_name='盤點日期')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登錄人')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='em.equip', verbose_name='設備')),
            ],
        ),
        migrations.AddField(
            model_name='equip',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='em.model'),
        ),
        migrations.RunPython(load_init_data),
    ]
